
import type { Assessment } from './types';

export const assessments: Assessment[] = [
  {
    id: 'asm-1',
    title: 'Cognitive Distortions Quiz',
    description: 'Identify common negative thought patterns.',
    type: 'MCQ',
    topic: 'Mental Wellness',
    difficulty: 'Beginner',
    estimatedTime: 10,
    status: 'Completed',
    contentUrls: [],
  },
  {
    id: 'asm-2',
    title: 'Effective Study Techniques',
    description: 'Learn and test your knowledge on proven study methods.',
    type: 'Video + Quiz',
    topic: 'Academic Skills',
    difficulty: 'Intermediate',
    estimatedTime: 25,
    status: 'In Progress',
    contentUrls: ['https://www.youtube.com/watch?v=somevideo'],
  },
  {
    id: 'asm-3',
    title: 'Mindfulness & Breathing Exercise',
    description: 'A guided session to practice mindfulness.',
    type: 'Reading + Essay',
    topic: 'Mental Wellness',
    difficulty: 'Beginner',
    estimatedTime: 15,
    status: 'Not Started',
    contentUrls: ['/path/to/breathing-guide.pdf'],
  },
  {
    id: 'asm-4',
    title: 'Social Anxiety Scenarios',
    description: 'Review common social scenarios and provide feedback.',
    type: 'Peer Review',
    topic: 'Social Skills',
    difficulty: 'Intermediate',
    estimatedTime: 20,
    status: 'Not Started',
    contentUrls: [],
  },
  {
    id: 'asm-5',
    title: 'Time Management Fundamentals',
    description: 'Assess your ability to prioritize tasks and manage your schedule.',
    type: 'MCQ',
    topic: 'Productivity',
    difficulty: 'Beginner',
    estimatedTime: 15,
    status: 'Not Started',
    contentUrls: [],
  },
   {
    id: 'asm-6',
    title: 'Critical Thinking Challenge',
    description: 'Analyze an article and write a critical response.',
    type: 'Reading + Essay',
    topic: 'Academic Skills',
    difficulty: 'Advanced',
    estimatedTime: 45,
    status: 'Not Started',
    contentUrls: ['/path/to/article.pdf'],
  },
];
